'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class BOSSinvtotEF
    Public Property invtotID As Integer
    Public Property tot_ukey As String
    Public Property tot_custid As String
    Public Property tot_invno As String
    Public Property tot_change As Nullable(Of Integer)
    Public Property tot_crsref As String
    Public Property tot_br As String
    Public Property tot_pono As String
    Public Property tot_costc As String
    Public Property tot_type As String
    Public Property tot_invdt As Nullable(Of Date)
    Public Property tot_duedt As Nullable(Of Date)
    Public Property tot_fare As Nullable(Of Decimal)
    Public Property tot_tax As Nullable(Of Decimal)
    Public Property tot_srvchg As Nullable(Of Decimal)
    Public Property tot_ourchg As Nullable(Of Decimal)
    Public Property tot_ourvat As Nullable(Of Decimal)
    Public Property tot_supvat As Nullable(Of Decimal)
    Public Property tot_amtvat As Nullable(Of Decimal)
    Public Property tot_bilvat As Nullable(Of Decimal)
    Public Property tot_amount As Nullable(Of Decimal)
    Public Property tot_billed As Nullable(Of Decimal)
    Public Property tot_discnt As Nullable(Of Decimal)
    Public Property tot_ccamt As Nullable(Of Decimal)
    Public Property tot_recvd As Nullable(Of Decimal)
    Public Property tot_dposit As Nullable(Of Decimal)
    Public Property tot_comm As Nullable(Of Decimal)
    Public Property tot_comdue As Nullable(Of Decimal)
    Public Property tot_vtoncm As Nullable(Of Decimal)
    Public Property tot_disput As Nullable(Of Boolean)
    Public Property tot_reason As String
    Public Property tot_noerrs As Nullable(Of Boolean)
    Public Property tot_note As String
    Public Property tot_raddr As String
    Public Property tot_rtelno As String
    Public Property tot_paxs As Nullable(Of Integer)
    Public Property tot_morcrs As String
    Public Property tot_retail As Nullable(Of Boolean)
    Public Property tot_bdm As String
    Public Property tot_print As Nullable(Of Integer)
    Public Property tot_errs As Nullable(Of Boolean)
    Public Property tot_atol As Nullable(Of Boolean)
    Public Property tot_atolx As String
    Public Property tot_cref1 As String
    Public Property tot_cref2 As String
    Public Property tot_agcomm As Nullable(Of Decimal)
    Public Property tot_agvat As Nullable(Of Decimal)
    Public Property tot_fileno As String
    Public Property tot_nofee As Nullable(Of Boolean)
    Public Property tot_crstyp As String
    Public Property tot_noprnt As Nullable(Of Boolean)
    Public Property tot_email As String
    Public Property tot_curncy As String
    Public Property tot_roe As Nullable(Of Decimal)
    Public Property tot_cursym As String
    Public Property datecreated As Nullable(Of Date)

End Class
