'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class EvolviDataEF
    Public Property EvolviDataID As Integer
    Public Property Ref As Nullable(Of Integer)
    Public Property ExternalRef As String
    Public Property IssueRef As Nullable(Of Integer)
    Public Property TransactionType As String
    Public Property TransactionDate As String
    Public Property MachineType As Nullable(Of Integer)
    Public Property MachineNumber As String
    Public Property CurrencyCode As String
    Public Property PersonalCCUsed As String
    Public Property FulfilmentType As String
    Public Property AccountRef As Nullable(Of Integer)
    Public Property AccountExternalRef As String
    Public Property AccountType As String
    Public Property Period As String
    Public Property Immediate As String
    Public Property EvolviInvoice As String
    Public Property EvolviPayment As String
    Public Property EvolviFinancial As String
    Public Property BookingAgentRef As Nullable(Of Integer)
    Public Property BookingAgentExternalRef As String
    Public Property BranchExternalRef As String
    Public Property Unit As String
    Public Property TicketingAgentRef As Nullable(Of Integer)
    Public Property TicketingAgentExternalRef As String
    Public Property TicketingAgentBranchExternalRef As String
    Public Property TicketingAgentUnit As String
    Public Property LeadRef As Nullable(Of Integer)
    Public Property AccountContactRef As Nullable(Of Integer)
    Public Property AccountContactFirstName As String
    Public Property AccountContactLastName As String
    Public Property AccountContactTitle As String
    Public Property AccountContactNumber As String
    Public Property AccountContactEmail As String
    Public Property AccountContactOrganisation As String
    Public Property AccountContactAddress1 As String
    Public Property AccountContactAddress2 As String
    Public Property AccountContactAddress3 As String
    Public Property AccountContactCity As String
    Public Property AccountContactCounty As String
    Public Property AccountContactPostcode As String
    Public Property DeliveryContactRef As Nullable(Of Integer)
    Public Property DeliveryContactFirstName As String
    Public Property DeliveryContactLastName As String
    Public Property DeliveryContactTitle As String
    Public Property DeliveryContactNumber As String
    Public Property DeliveryContactEmail As String
    Public Property DeliveryContactOrganisation As String
    Public Property DeliveryContactAddress1 As String
    Public Property DeliveryContactAddress2 As String
    Public Property DeliveryContactAddress3 As String
    Public Property DeliveryContactCity As String
    Public Property DeliveryContactCounty As String
    Public Property DeliveryContactPostcode As String
    Public Property datecreated As Nullable(Of Date)
    Public Property lastupdated As Nullable(Of Date)
    Public Property createdby As String
    Public Property updatedby As String
    Public Property BookingAgentFirstName As String
    Public Property BookingAgentLastName As String
    Public Property BookingAgentTitle As String
    Public Property BookingAgentEmailAddress As String
    Public Property OnBehalfRef As Nullable(Of Integer)
    Public Property OnBehalfExternalRef As String
    Public Property OnBehalfBranchExternalRef As String
    Public Property OnBehalfUnit As String
    Public Property OnBehalfFirstName As String
    Public Property OnBehalfLastName As String
    Public Property OnBehalfTitle As String
    Public Property OnBehalfEmailAddress As String
    Public Property Deleted As Nullable(Of Boolean)

End Class
