'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class InterceptorCharges
    Public Property ID As Integer
    Public Property IssueRef As String
    Public Property TotalTickets As Nullable(Of Integer)
    Public Property TransactionFee As Nullable(Of Decimal)
    Public Property TransactionFeeTotal As Nullable(Of Decimal)
    Public Property PostageFee As Nullable(Of Decimal)
    Public Property PostageFeeTotal As Nullable(Of Decimal)
    Public Property OfflineFee As Nullable(Of Decimal)
    Public Property OfflineFeeTotal As Nullable(Of Decimal)
    Public Property SpecialDeliveryFee As Nullable(Of Decimal)
    Public Property SpecialDeliveryFeeTotal As Nullable(Of Decimal)
    Public Property CancellationFee As Nullable(Of Decimal)
    Public Property CancellationFeeTotal As Nullable(Of Decimal)
    Public Property IssueType As String
    Public Property IssueDate As String
    Public Property ClientBossCode As String
    Public Property ToDFee As Nullable(Of Decimal)
    Public Property ToDFeeTotal As Nullable(Of Decimal)
    Public Property KioskFee As Nullable(Of Decimal)
    Public Property KioskFeeTotal As Nullable(Of Decimal)
    Public Property SaturdaySDFee As Nullable(Of Decimal)
    Public Property SaturdaySDFeeTotal As Nullable(Of Decimal)
    Public Property CourierFee As Nullable(Of Decimal)
    Public Property CourierFeeTotal As Nullable(Of Decimal)
    Public Property PlainPaperTicketingFee As Nullable(Of Decimal)
    Public Property PlainPaperTicketingFeeTotal As Nullable(Of Decimal)

End Class
