'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class NYSDBEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=NYSDBEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property ChiesiGLIOCodes() As DbSet(Of ChiesiGLIOCodes)
    Public Overridable Property EvolviDataEF() As DbSet(Of EvolviDataEF)
    Public Overridable Property TravellerProfiles() As DbSet(Of TravellerProfiles)
    Public Overridable Property InterceptorCharges() As DbSet(Of InterceptorCharges)
    Public Overridable Property interceptorClients() As DbSet(Of interceptorClients)
    Public Overridable Property BOSSinvtotEF() As DbSet(Of BOSSinvtotEF)

End Class
