'R2.18 CR - Essentially just renamed the admin_autogenerated class to clsClientStatementDetails

Imports EvoDatabaseUtils
Imports EvoUtilities.ConfigUtils
Public Class clsClientStatementDetails
    Public Sub New()
    End Sub

    Private mClientID As Integer
    Private mBossRef As String
    Private mEmailAddress As String
    Private mReferenceColumn As String
    Private mSendEmail As Boolean
    Private mConsolFileLocation As String

    Public Sub New(ByVal pEmailAddress As String, _
                    ByVal pReference As String, _
                    ByVal pSendEmail As Boolean, _
                    ByVal pFilelocation As String)
        mEmailAddress = pEmailAddress
        mReferenceColumn = pReference
        mSendEmail = pSendEmail
        mConsolFileLocation = pFilelocation
    End Sub

    Public Sub New(ByVal pBossRef As String)
        mBossRef = pBossRef
    End Sub

    'R2.20D SA
    Private mRefrerenceColumn2 As String
    Public Property ReferenceColumn2() As String
        Get
            Return mRefrerenceColumn2
        End Get
        Set(ByVal value As String)
            mRefrerenceColumn2 = value
        End Set
    End Property

    Public Property ClientID As Integer
        Get
            Return mClientID
        End Get
        Set(value As Integer)
            mClientID = value
        End Set
    End Property

    Public Property BossRef As String
        Get
            Return mBossRef
        End Get
        Set(value As String)
            mBossRef = value
        End Set
    End Property

    Public Property EmailAddress As String
        Get
            Return mEmailAddress
        End Get
        Set(value As String)
            mEmailAddress = value
        End Set
    End Property

    Public Property ReferenceColumn As String
        Get
            Return mReferenceColumn
        End Get
        Set(value As String)
            mReferenceColumn = value
        End Set
    End Property

    Public Property SendEmail As Boolean
        Get
            Return mSendEmail
        End Get
        Set(value As Boolean)
            mSendEmail = value
        End Set
    End Property

    Public Property ConsolFileLocation As String
        Get
            Return mConsolFileLocation
        End Get
        Set(value As String)
            mConsolFileLocation = value
        End Set
    End Property

    Private Shared Function makeBossCodeFromRow(ByVal r As IDataReader) As clsClientStatementDetails
        Return New clsClientStatementDetails(toStr(r.Item("csd_BossRef")))
    End Function

    Public Shared Function listBossRef() As List(Of clsClientStatementDetails)
        Using dbh As New SqlDatabaseHandle(getConfig("ConnectionString"))
            Dim ret As New List(Of clsClientStatementDetails)()
            Using r As IDataReader = dbh.callSP("ClientStatementDetails_listBossRef")
                While r.Read()
                    ret.Add(makeBossCodeFromRow(r))
                End While
            End Using
            Return ret
        End Using
    End Function

    Public Shared Function getDetails(ByVal pBossRef As String) As clsClientStatementDetails
        Using dbh As New SqlDatabaseHandle(getConfig("ConnectionString"))
            Dim details As New clsClientStatementDetails
            Using r As IDataReader = dbh.callSP("ClientStatementDetails_getDetails", _
                                                                "@csd_BossRef", pBossRef)
                While r.Read()
                    With details
                        .mEmailAddress = clsNYS.notString(r.Item("csd_EmailAddress"))
                        .mReferenceColumn = clsNYS.notString(r.Item("csd_Reference"))
                        .mSendEmail = clsNYS.notBoolean(r.Item("csd_SendtoEmail"))
                        .mConsolFileLocation = clsNYS.notString(r.Item("csd_CI_FileLocation"))
                        .mRefrerenceColumn2 = clsNYS.notString(r.Item("csd_Reference2"))
                    End With
                End While
            End Using
            Return details
        End Using
    End Function

    Public Shared Function getID(ByVal pBossRef As String) As Integer
        Using dbh As New SqlDatabaseHandle(getConfig("ConnectionString"))
            Dim intRet As Integer = CInt(dbh.callSPSingleValue("ClientStatementDetails_getID", _
                                                                "@csd_BossRef", pBossRef))

            Return intRet
        End Using
    End Function

    Public Shared Function getEmail(ByVal pBossRef As String) As String
        Using dbh As New SqlDatabaseHandle(getConfig("ConnectionString"))
            Dim strRet As String = CStr(dbh.callSPSingleValue("ClientStatementDetails_getEmailAddress", _
                                                    "@csd_BossRef", pBossRef))
            Return strRet
        End Using
    End Function

    Public Shared Function getFileLocation(ByVal pBossRef As String) As String
        Using dbh As New SqlDatabaseHandle(getConfig("ConnectionString"))
            Dim strRet As String = dbh.callSPSingleValueCanReturnNothing("ClientStatementDetails_getFileLocation", _
                                                                               "@csd_BossRef", pBossRef)
            Return strRet
        End Using
    End Function

    Public Shared Function update(ByVal pID As Integer, _
                                 ByVal pBossRef As String, _
                                 ByVal pEmailAddress As String, _
                                 ByVal pReference As String, _
                                 ByVal pSendtoEmail As Boolean,
                                 ByVal pFileLocation As String, _
                                 ByVal pReference2 As String) As Boolean
        Using dbh As New SqlDatabaseHandle(getConfig("ConnectionString"))
            Dim blnRet As Boolean = CBool(dbh.callSPSingleValue("ClientStatementDetails_update", _
                                                               "@csd_ID", pID, _
                                                               "@csd_BossRef", pBossRef, _
                                                               "@csd_EmailAddress", pEmailAddress, _
                                                               "@csd_Reference", pReference, _
                                                               "@csd_SendtoEmail", pSendtoEmail, _
                                                               "@csd_CI_FileLocation", pFileLocation, _
                                                               "@csd_Reference2", pReference2))
            Return blnRet
        End Using
    End Function


End Class
