'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class FeedTransactionEF
    Public Property transactionid As Integer
    Public Property transactioncode As String
    Public Property transactionvalue As Nullable(Of Double)
    Public Property datecreated As Nullable(Of Date)
    Public Property lastupdated As Nullable(Of Date)
    Public Property transactiontype As String
    Public Property CountryCode As String
    Public Property Commissionable As Nullable(Of Boolean)

End Class
