'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class FeedParameterEF
    Public Property parameterid As Integer
    Public Property groupid As Nullable(Of Integer)
    Public Property parameterstart As Nullable(Of Date)
    Public Property parameterend As Nullable(Of Date)
    Public Property transactionid As Nullable(Of Integer)
    Public Property datecreated As Nullable(Of Date)
    Public Property lastupdated As Nullable(Of Date)

End Class
