//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CostImprovementAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class BreakdownOfSavings
    {
        public int SchemeID { get; set; }
        public string BudgetTypeNameA { get; set; }
        public string BudgetTypeNameB { get; set; }
        public Nullable<decimal> WTE { get; set; }
        public Nullable<decimal> Year1Saving { get; set; }
        public Nullable<decimal> ReccurentSavingValue { get; set; }
        public string TrustCode { get; set; }
    
        public virtual BudgetType BudgetType { get; set; }
        public virtual BudgetType BudgetType1 { get; set; }
        public virtual CiaForm CiaForm { get; set; }
    }
}
