//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CostImprovementAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessLevel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BusinessLevel()
        {
            this.CiaForm = new HashSet<CiaForm>();
        }
    
        public string BusinesslevelName { get; set; }
        public string BusinessSectorName { get; set; }
        public string DepartmentName { get; set; }
        public string TrustCode { get; set; }
    
        public virtual BusinessSector BusinessSector { get; set; }
        public virtual Department Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CiaForm> CiaForm { get; set; }
        public virtual Trusts Trusts { get; set; }
    }
}
