//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CostImprovementAssistant
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ciaEntities : DbContext
    {
        public ciaEntities()
            : base("name=ciaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Assumptions> Assumptions { get; set; }
        public virtual DbSet<BreakdownOfEnablingCosts> BreakdownOfEnablingCosts { get; set; }
        public virtual DbSet<BreakdownOfSavings> BreakdownOfSavings { get; set; }
        public virtual DbSet<BudgetType> BudgetType { get; set; }
        public virtual DbSet<BusinessLevel> BusinessLevel { get; set; }
        public virtual DbSet<BusinessSector> BusinessSector { get; set; }
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<CiaForm> CiaForm { get; set; }
        public virtual DbSet<Department> Department { get; set; }
        public virtual DbSet<Dependencies> Dependencies { get; set; }
        public virtual DbSet<GeneratedIncome> GeneratedIncome { get; set; }
        public virtual DbSet<Impact> Impact { get; set; }
        public virtual DbSet<Issues> Issues { get; set; }
        public virtual DbSet<KpiaSourcesReporting> KpiaSourcesReporting { get; set; }
        public virtual DbSet<Milestones> Milestones { get; set; }
        public virtual DbSet<QiConditions> QiConditions { get; set; }
        public virtual DbSet<QiConditionTable> QiConditionTable { get; set; }
        public virtual DbSet<QualityImpact> QualityImpact { get; set; }
        public virtual DbSet<QualityIndicators> QualityIndicators { get; set; }
        public virtual DbSet<SchemeKpia> SchemeKpia { get; set; }
        public virtual DbSet<SchemeQualityIndicators> SchemeQualityIndicators { get; set; }
        public virtual DbSet<SchemeRisks> SchemeRisks { get; set; }
        public virtual DbSet<Staff> Staff { get; set; }
        public virtual DbSet<Stakeholders> Stakeholders { get; set; }
        public virtual DbSet<SchemeBudgetTypes> SchemeBudgetTypes { get; set; }
        public virtual DbSet<Trusts> Trusts { get; set; }
    }
}
