//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CostImprovementAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class CiaForm
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CiaForm()
        {
            this.BreakdownOfEnablingCosts = new HashSet<BreakdownOfEnablingCosts>();
            this.BreakdownOfSavings = new HashSet<BreakdownOfSavings>();
            this.SchemeKpia = new HashSet<SchemeKpia>();
            this.SchemeQualityIndicators = new HashSet<SchemeQualityIndicators>();
            this.GeneratedIncome = new HashSet<GeneratedIncome>();
            this.Issues = new HashSet<Issues>();
            this.Milestones = new HashSet<Milestones>();
            this.SchemeRisks = new HashSet<SchemeRisks>();
            this.Stakeholders = new HashSet<Stakeholders>();
        }
    
        public int SchemeID { get; set; }
        public Nullable<System.DateTime> DateofScheme { get; set; }
        public string SchemeName { get; set; }
        public string CategoryName { get; set; }
        public string DepartmentName { get; set; }
        public string BusinessLevelName { get; set; }
        public string BusinessSectorName { get; set; }
        public string Overview { get; set; }
        public string CurrentState { get; set; }
        public string TargetState { get; set; }
        public string ProjectSupervisor { get; set; }
        public string ProjectManager { get; set; }
        public string BudgetSupervisor { get; set; }
        public string HrSupervisor { get; set; }
        public string ExecutiveOwner { get; set; }
        public Nullable<decimal> ConfidenceFactor { get; set; }
        public Nullable<System.DateTime> ImplementationDate { get; set; }
        public Nullable<decimal> BenefitExpectedInCiaYear { get; set; }
        public Nullable<decimal> ReccuringAnualBenefit { get; set; }
        public Nullable<decimal> EnablingCosts { get; set; }
        public Nullable<decimal> NettCiaYearSavings { get; set; }
        public string PSAuthorisationCode { get; set; }
        public Nullable<System.DateTime> PSAuthorisationDate { get; set; }
        public string BSAuthorisationCode { get; set; }
        public Nullable<System.DateTime> BSAuthorisationDate { get; set; }
        public decimal RiskAdjustedValue { get; set; }
        public string ConfidenceCode { get; set; }
        public string TrustCode { get; set; }
        public bool Active { get; set; }
        public bool QIRequired { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BreakdownOfEnablingCosts> BreakdownOfEnablingCosts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BreakdownOfSavings> BreakdownOfSavings { get; set; }
        public virtual BusinessLevel BusinessLevel { get; set; }
        public virtual BusinessSector BusinessSector { get; set; }
        public virtual Category Category { get; set; }
        public virtual QualityImpact QualityImpact { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SchemeKpia> SchemeKpia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SchemeQualityIndicators> SchemeQualityIndicators { get; set; }
        public virtual Department Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GeneratedIncome> GeneratedIncome { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Issues> Issues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Milestones> Milestones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SchemeRisks> SchemeRisks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stakeholders> Stakeholders { get; set; }
        public virtual Trusts Trusts { get; set; }
    }
}
