//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CostImprovementAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class Issues
    {
        public int SchemeID { get; set; }
        public int IssueID { get; set; }
        public string IssueDetail { get; set; }
        public string Impact { get; set; }
        public string TrustCode { get; set; }
    
        public virtual CiaForm CiaForm { get; set; }
        public virtual Impact Impact1 { get; set; }
        public virtual Trusts Trusts { get; set; }
    }
}
