//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CostImprovementAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class Milestones
    {
        public int SchemeID { get; set; }
        public int MilestonesID { get; set; }
        public string MilestonesDetail { get; set; }
        public Nullable<System.DateTime> ExpectedCompletionDate { get; set; }
        public Nullable<System.DateTime> RevisedDate { get; set; }
        public string RevisionReason { get; set; }
        public Nullable<System.DateTime> DateOFCompletion { get; set; }
        public string TrustCode { get; set; }
    
        public virtual CiaForm CiaForm { get; set; }
    }
}
