//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CostImprovementAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchemeQualityIndicators
    {
        public int SchemeID { get; set; }
        public string QualityIndicatorsTitle { get; set; }
        public string TrustCode { get; set; }
    
        public virtual CiaForm CiaForm { get; set; }
    }
}
