//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CostImprovementAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public int StaffID { get; set; }
        public string StaffName { get; set; }
        public string Email { get; set; }
        public string StaffPassword { get; set; }
        public Nullable<bool> Administrator { get; set; }
        public Nullable<bool> PM { get; set; }
        public Nullable<bool> PS { get; set; }
        public Nullable<bool> BS { get; set; }
        public Nullable<bool> HR { get; set; }
        public Nullable<bool> EO { get; set; }
        public Nullable<bool> CompletingQI { get; set; }
        public Nullable<bool> ReviewingQI { get; set; }
        public Nullable<bool> ChiefNursing { get; set; }
        public Nullable<bool> Spare1 { get; set; }
        public Nullable<bool> Spare2 { get; set; }
        public Nullable<bool> Active { get; set; }
        public string TrustCode { get; set; }
    }
}
