'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class IAAdminEvolvi

    '''<summary>
    '''Head1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Head1 As Global.System.Web.UI.HtmlControls.HtmlHead

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''pnTrans control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnTrans As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''pnNav control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnNav As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''btnlogout control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnlogout As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''HoverMenuExtender1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HoverMenuExtender1 As Global.AjaxControlToolkit.HoverMenuExtender

    '''<summary>
    '''phMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phMenu As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''pnlMain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlMain As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''imHover control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imHover As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''pnlSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSearch As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblGroup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGroup As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddGroup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddGroup As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lnkAddNewClient control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkAddNewClient As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''pnlDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlDetails As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblClientName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblClientName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtClientName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtClientName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblBossCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBossCode As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtBossCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBossCode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblInterceptorFeesActive control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInterceptorFeesActive As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''chkInterceptorFeesActive control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkInterceptorFeesActive As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblInterceptorDiscountActive control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInterceptorDiscountActive As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''chkInterceptorDiscountActive control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkInterceptorDiscountActive As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''Label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtDiscountPercentage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDiscountPercentage As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPerTicket control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPerTicket As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPerPax control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPerPax As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPerOrderItem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPerOrderItem As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPerbasket control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPerbasket As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblKisokOnlineFee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblKisokOnlineFee As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtKioskOnlineFeePerTicket control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtKioskOnlineFeePerTicket As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtKioskOnlineFeePerPax control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtKioskOnlineFeePerPax As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtKioskOnlineFeePerOrderItem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtKioskOnlineFeePerOrderItem As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtKioskOnlineFeePerBasket control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtKioskOnlineFeePerBasket As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblKisokOfflineFee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblKisokOfflineFee As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtKioskOfflineFeePerTicket control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtKioskOfflineFeePerTicket As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtKioskOfflineFeePerPax control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtKioskOfflineFeePerPax As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtKioskOfflineFeePerOrderItem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtKioskOfflineFeePerOrderItem As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtKioskOfflineFeePerBasket control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtKioskOfflineFeePerBasket As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblToDOnlineFee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblToDOnlineFee As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtToDOnlineFeePerTicket control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtToDOnlineFeePerTicket As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtToDOnlineFeePerPax control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtToDOnlineFeePerPax As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtToDOnlineFeePerOrderItem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtToDOnlineFeePerOrderItem As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtToDOnlineFeePerBasket control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtToDOnlineFeePerBasket As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblToDOfflineFee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblToDOfflineFee As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtToDOfflineFeePerTicket control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtToDOfflineFeePerTicket As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtToDOfflineFeePerPax control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtToDOfflineFeePerPax As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtToDOfflineFeePerOrderItem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtToDOfflineFeePerOrderItem As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtToDOfflineFeePerBasket control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtToDOfflineFeePerBasket As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblPostageOnlineFee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPostageOnlineFee As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPostageOnlineFeePerTicket control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPostageOnlineFeePerTicket As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPostageOnlineFeePerPax control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPostageOnlineFeePerPax As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPostageOnlineFeePerOrderItem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPostageOnlineFeePerOrderItem As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPostageOnlineFeePerBasket control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPostageOnlineFeePerBasket As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblPostageOfflineFee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPostageOfflineFee As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPostageOfflineFeePerTicket control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPostageOfflineFeePerTicket As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPostageOfflineFeePerPax control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPostageOfflineFeePerPax As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPostageOfflineFeePerOrderItem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPostageOfflineFeePerOrderItem As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPostageOfflineFeePerBasket control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPostageOfflineFeePerBasket As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblCourierOnlineFee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCourierOnlineFee As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtCourierOnlineFeePerTicket control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCourierOnlineFeePerTicket As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCourierOnlineFeePerPax control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCourierOnlineFeePerPax As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCourierOnlineFeePerOrderItem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCourierOnlineFeePerOrderItem As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCourierOnlineFeePerBasket control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCourierOnlineFeePerBasket As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblCourierOfflineFee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCourierOfflineFee As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtCourierOfflineFeePerTicket control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCourierOfflineFeePerTicket As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCourierOfflineFeePerPax control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCourierOfflineFeePerPax As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCourierOfflineFeePerOrderItem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCourierOfflineFeePerOrderItem As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCourierOfflineFeePerBasket control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCourierOfflineFeePerBasket As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblSpecialDeliveryOnlineFee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSpecialDeliveryOnlineFee As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtSDOnlineFeePerTicket control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSDOnlineFeePerTicket As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtSDOnlineFeePerPax control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSDOnlineFeePerPax As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtSDOnlineFeePerOrderItem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSDOnlineFeePerOrderItem As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtSDOnlineFeePerBasket control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSDOnlineFeePerBasket As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblSpecialDeliveryOfflineFee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSpecialDeliveryOfflineFee As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtSDOfflineFeePerTicket control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSDOfflineFeePerTicket As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtSDOfflineFeePerPax control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSDOfflineFeePerPax As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtSDOfflineFeePerOrderItem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSDOfflineFeePerOrderItem As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtSDOfflineFeePerBasket control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSDOfflineFeePerBasket As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblSatSpecialDeliveryOnlineFee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSatSpecialDeliveryOnlineFee As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtSSDOnlineFeePerTicket control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSSDOnlineFeePerTicket As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtSSDOnlineFeePerPax control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSSDOnlineFeePerPax As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtSSDOnlineFeePerOrderItem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSSDOnlineFeePerOrderItem As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtSSDOnlineFeePerBasket control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSSDOnlineFeePerBasket As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblSatSpecialDeliveryOfflineFee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSatSpecialDeliveryOfflineFee As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtSSDOfflineFeePerTicket control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSSDOfflineFeePerTicket As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtSSDOfflineFeePerPax control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSSDOfflineFeePerPax As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtSSDOfflineFeePerOrderItem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSSDOfflineFeePerOrderItem As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtSSDOfflineFeePerBasket control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSSDOfflineFeePerBasket As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblBooker control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBooker As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''chkBooker control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkBooker As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblCutomPO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCutomPO As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''chkCustomPO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkCustomPO As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblCustomPoValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCustomPoValue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtCustomPO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCustomPO As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblSplitBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSplitBy As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddSplitNode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddSplitNode As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblSplitOnAttribute control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSplitOnAttribute As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtSplitField control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSplitField As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtSplitFieldValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSplitFieldValue As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtUniqueFieldName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtUniqueFieldName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''pnlButtons control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlButtons As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''btnSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSave As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAdd As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancel As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblBookingDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBookingDetails As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlClientID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlClientID As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''hdnClientID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnClientID As Global.System.Web.UI.WebControls.HiddenField
End Class
