'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ad_hotelChecker_temp
    Public Property tempID As Integer
    Public Property ConfermaRef As Integer
    Public Property Client As String
    Public Property groupid As Nullable(Of Integer)
    Public Property HotelID As Nullable(Of Integer)
    Public Property Hotel As String
    Public Property Telephone As String
    Public Property RoomType As String
    Public Property Traveller As String
    Public Property Channel As String
    Public Property ArrivalDate As Nullable(Of Date)
    Public Property No_nights As Nullable(Of Integer)
    Public Property PNR As String

End Class
