'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ad_hotelChecker
    Public Property ID As Integer
    Public Property dataid As Integer
    Public Property hotelcontact As String
    Public Property outcome As Nullable(Of Integer)
    Public Property outcome_post As Nullable(Of Integer)
    Public Property Notes As String
    Public Property Processed As Nullable(Of Boolean)
    Public Property dateProcessed As Nullable(Of Date)
    Public Property isTemp As Boolean
    Public Property PNR As String

End Class
