'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class cima
    Public Property cimaid As Integer
    Public Property cimacode As String
    Public Property department As String
    Public Property directorate As String
    Public Property type As String

End Class
