'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ClientMappings
    Public Property ClientMappingsID As Integer
    Public Property ClientID As Nullable(Of Integer)
    Public Property CostCentreValue As String
    Public Property CostCentreDefault As String
    Public Property POValue As String
    Public Property PODefault As String
    Public Property CREF1Value As String
    Public Property CREF1Default As String
    Public Property CREF2Value As String
    Public Property CREF2Default As String
    Public Property CREF3Value As String
    Public Property CREF3Default As String
    Public Property CREF4Value As String
    Public Property CREF5Value As String
    Public Property CREF6Value As String
    Public Property CREF7Value As String
    Public Property CREF8Value As String
    Public Property CREF9Value As String
    Public Property CREF9Default As String
    Public Property CREF8Default As String
    Public Property CREF7Default As String
    Public Property CREF6Default As String
    Public Property CREF5Default As String
    Public Property CREF4Default As String

End Class
