'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ConfirmaImport
    Public Property ConfirmaImportID As Integer
    Public Property TransactionNumber As Nullable(Of Integer)
    Public Property TransactionLineNumber As Nullable(Of Integer)
    Public Property TransactionDate As Nullable(Of Date)
    Public Property DepartureDate As Nullable(Of Date)
    Public Property ArrivalDate As Nullable(Of Date)
    Public Property LeadPassengerName As String
    Public Property BookingReference As String
    Public Property MajorDestination As String
    Public Property RefBooker As String
    Public Property Department As String
    Public Property TransactionType As String
    Public Property TransactionCurrency As String
    Public Property TotalSaleAmount As Nullable(Of Decimal)
    Public Property TotalSaleVatAmount As Nullable(Of Decimal)
    Public Property SaleVatCode As Nullable(Of Decimal)
    Public Property TotalBilledInGbp As Nullable(Of Decimal)
    Public Property PaymentMethod As String
    Public Property SupplierID As String
    Public Property SupplierName As String
    Public Property HotelDetails As String
    Public Property RoomDetails As String
    Public Property Company As String
    Public Property ConfermaInvoiceNo As String
    Public Property DESCRIPTION As String
    Public Property SupplierInvoiceRef As String
    Public Property CountryCode As String
    Public Property GuestPNR As String
    Public Property InvoiceLastModifiedDate As String
    Public Property BookedDate As String
    Public Property OutofPolicyReason As String
    Public Property Last4Digits As String
    Public Property TravellerEmail As String
    Public Property BookerEmail As String
    Public Property AIBkrName As String
    Public Property AICostCode As String
    Public Property AIBillInstruct As String
    Public Property AIComments As String
    Public Property AIAgentBkr As String
    Public Property AICol6 As String
    Public Property AICol7 As String
    Public Property AICol8 As String
    Public Property AICol9 As String
    Public Property AICol10 As String
    Public Property InvoiceLineDetailID As String
    Public Property ImportDate As Nullable(Of Date)

End Class
