'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CostCodeExp
    Public Property ccid As Integer
    Public Property groupid As Nullable(Of Integer)
    Public Property expression As String
    Public Property expressionFormat As String

End Class
