'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class CUBITEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=CUBITEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property ad_hotelCheck_outcomes() As DbSet(Of ad_hotelCheck_outcomes)
    Public Overridable Property ad_hotelChecker() As DbSet(Of ad_hotelChecker)
    Public Overridable Property ad_hotelChecker_temp() As DbSet(Of ad_hotelChecker_temp)
    Public Overridable Property ad_hotelstoIgnore() As DbSet(Of ad_hotelstoIgnore)
    Public Overridable Property ad_vipTravellers() As DbSet(Of ad_vipTravellers)
    Public Overridable Property cima() As DbSet(Of cima)
    Public Overridable Property ClientMappings() As DbSet(Of ClientMappings)
    Public Overridable Property ClientOptions() As DbSet(Of ClientOptions)
    Public Overridable Property code() As DbSet(Of code)
    Public Overridable Property CostCodeExp() As DbSet(Of CostCodeExp)
    Public Overridable Property EACTCodes() As DbSet(Of EACTCodes)
    Public Overridable Property EOECostCentre() As DbSet(Of EOECostCentre)
    Public Overridable Property FeedAmendment() As DbSet(Of FeedAmendment)
    Public Overridable Property FeedBookedData() As DbSet(Of FeedBookedData)
    Public Overridable Property FeedCategory() As DbSet(Of FeedCategory)
    Public Overridable Property FeedImportData() As DbSet(Of FeedImportData)
    Public Overridable Property FeedImportDataDuplicate() As DbSet(Of FeedImportDataDuplicate)
    Public Overridable Property FeedInvoice() As DbSet(Of FeedInvoice)
    Public Overridable Property FeedParameter() As DbSet(Of FeedParameter)
    Public Overridable Property FeedStatus() As DbSet(Of FeedStatus)
    Public Overridable Property FeedTransaction() As DbSet(Of FeedTransaction)
    Public Overridable Property FeedTransactionInvoice() As DbSet(Of FeedTransactionInvoice)
    Public Overridable Property NPSAProjectCode() As DbSet(Of NPSAProjectCode)
    Public Overridable Property PurposeCode() As DbSet(Of PurposeCode)
    Public Overridable Property SubClientOptions() As DbSet(Of SubClientOptions)
    Public Overridable Property sysdiagrams() As DbSet(Of sysdiagrams)
    Public Overridable Property TransactionData() As DbSet(Of TransactionData)
    Public Overridable Property TransactionData_oldData() As DbSet(Of TransactionData_oldData)
    Public Overridable Property UHSMCostcode() As DbSet(Of UHSMCostcode)
    Public Overridable Property VenueAlternate() As DbSet(Of VenueAlternate)
    Public Overridable Property DCCostCodes() As DbSet(Of DCCostCodes)
    Public Overridable Property LastDate() As DbSet(Of LastDate)
    Public Overridable Property LVCodes() As DbSet(Of LVCodes)
    Public Overridable Property ConfirmaImport() As DbSet(Of ConfirmaImport)

End Class
