'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class FeedCategory
    Public Property categoryid As Integer
    Public Property categorycode As Nullable(Of Integer)
    Public Property categoryname As String
    Public Property categorybosscode As String
    Public Property datecreated As Nullable(Of Date)
    Public Property lastupdated As Nullable(Of Date)

End Class
