'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class FeedInvoice
    Public Property invoiceid As Integer
    Public Property transactionnumber As Nullable(Of Integer)
    Public Property systemnysuserid As Nullable(Of Integer)
    Public Property invoiceexportednett As Nullable(Of Double)
    Public Property invoiceexportedvat As Nullable(Of Double)
    Public Property invoiceexportedgross As Nullable(Of Double)
    Public Property invoiceexport As Nullable(Of Boolean)
    Public Property invoiceexportdate As Nullable(Of Date)
    Public Property transactionfee As Nullable(Of Double)
    Public Property bossid As String
    Public Property bosstotal As Nullable(Of Double)
    Public Property bosscomNett As Nullable(Of Double)
    Public Property bosscomVat As Nullable(Of Double)
    Public Property datecreated As Nullable(Of Date)
    Public Property lastupdated As Nullable(Of Date)

End Class
