'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class FeedImportDataDuplicate
    Public Property dataid As Integer
    Public Property transactionnumber As Nullable(Of Integer)
    Public Property transactionlinenumber As Nullable(Of Integer)
    Public Property transactiondate As Nullable(Of Date)
    Public Property arrivaldate As Nullable(Of Date)
    Public Property departuredate As Nullable(Of Date)
    Public Property passengername As String
    Public Property ref1 As String
    Public Property ref2 As String
    Public Property ref3 As String
    Public Property dept As String
    Public Property booker As String
    Public Property bookerinitials As String
    Public Property nettamount As Nullable(Of Double)
    Public Property vatamount As Nullable(Of Double)
    Public Property vatrate As Nullable(Of Double)
    Public Property totalamount As Nullable(Of Double)
    Public Property venuename As String
    Public Property venuedetails As String
    Public Property roomdetails As String
    Public Property groupid As Nullable(Of Integer)
    Public Property groupname As String
    Public Property confermainvoicenumber As Nullable(Of Integer)
    Public Property categoryid As Nullable(Of Integer)
    Public Property supplierinvoice As String
    Public Property guestPNR As String
    Public Property costcode As String
    Public Property parameterid As Nullable(Of Integer)
    Public Property venuereference As Nullable(Of Integer)
    Public Property venuebosscode As String
    Public Property venueEX As Nullable(Of Double)
    Public Property venueDD As Nullable(Of Double)
    Public Property statusid As Nullable(Of Integer)
    Public Property transactionvaluenew As String
    Public Property failreason As String
    Public Property BookedDate As Nullable(Of Date)
    Public Property datecreated As Nullable(Of Date)
    Public Property lastupdated As Nullable(Of Date)
    Public Property AICol6 As String
    Public Property AICol7 As String
    Public Property AICol8 As String
    Public Property AICol9 As String
    Public Property AICol10 As String
    Public Property currency As String
    Public Property cancellation As Nullable(Of Boolean)
    Public Property excludeFromExport As Nullable(Of Boolean)
    Public Property Last4Digits As String
    Public Property OutofPolicyReason As String
    Public Property complaintsText As String
    Public Property TravellerEmail As String
    Public Property BookerEmail As String

End Class
