'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class FeedBookedData
    Public Property dataid As Integer
    Public Property BookingId As Nullable(Of Integer)
    Public Property LineNumber As Nullable(Of Integer)
    Public Property BookedDate As Nullable(Of Date)
    Public Property ArrivalDate As Nullable(Of Date)
    Public Property DepartureDate As Nullable(Of Date)
    Public Property LeadPassengerName As String
    Public Property BookingReference As String
    Public Property MajorDestination As String
    Public Property RefBooker As String
    Public Property TransactionCurrency As String
    Public Property TotalSaleAmount As Nullable(Of Double)
    Public Property TotalBilledInGbp As Nullable(Of Double)
    Public Property PaymentMethod As String
    Public Property SupplierID As Nullable(Of Integer)
    Public Property SupplierName As String
    Public Property HotelDetails As String
    Public Property RoomDetails As String
    Public Property groupid As Nullable(Of Integer)
    Public Property groupname As String
    Public Property CountryCode As String
    Public Property GuestPNR As String
    Public Property Channel As String
    Public Property Creator As String
    Public Property CreatorCompany As String
    Public Property AIBkrName As String
    Public Property AICostCode As String
    Public Property AIBillInstruct As String
    Public Property AIComments As String
    Public Property AIAgentBkr As String
    Public Property AICol6 As String
    Public Property AICol7 As String
    Public Property AICol8 As String
    Public Property AICol9 As String
    Public Property AICol10 As String
    Public Property datecreated As Nullable(Of Date)
    Public Property currentstatus As String
    Public Property dateEmailSent As String
    Public Property dontsend As Nullable(Of Boolean)
    Public Property unabletosend As Nullable(Of Boolean)
    Public Property unabletosendreason As String
    Public Property AmendedDate As String
    Public Property AmendedByPerson As String
    Public Property CancellationDate As String
    Public Property CancelledByPerson As String
    Public Property OutofPolicyReason As String
    Public Property Last4Digits As String
    Public Property TravellerEmail As String
    Public Property BookerEmail As String
    Public Property TransferredtoImportData As Nullable(Of Boolean)

End Class
