'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class FeedTransactionInvoice
    Public Property TransactionId As Integer
    Public Property InvoiceId As Integer
    Public Property BOSSTotal As Nullable(Of Double)
    Public Property BOSSCommNett As Nullable(Of Double)
    Public Property BOSSCommVAT As Nullable(Of Double)
    Public Property BOSSId As String

End Class
