'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class FeedAmendment
    Public Property amendmentid As Integer
    Public Property systemnysuserid As Nullable(Of Integer)
    Public Property dataid As Nullable(Of Integer)
    Public Property amendmentdate As Nullable(Of Date)
    Public Property amendmentvalueold As String
    Public Property amendmentvaluenew As String
    Public Property oldreference As Nullable(Of Integer)
    Public Property reference As Nullable(Of Integer)
    Public Property oldvenuename As String
    Public Property venuename As String
    Public Property oldbosscode As String
    Public Property bosscode As String
    Public Property oldEX As Nullable(Of Double)
    Public Property commissionEX As Nullable(Of Double)
    Public Property oldDD As Nullable(Of Double)
    Public Property commissionDD As Nullable(Of Double)
    Public Property olddatacostcode As String
    Public Property datacostcode As String
    Public Property datecreated As Nullable(Of Date)
    Public Property lastupdated As Nullable(Of Date)
    Public Property oldTravellerEmail As String

End Class
