'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class SubClientOptions
    Public Property SubClientID As Integer
    Public Property SubClientName As String
    Public Property SubClientBossCode As String
    Public Property GroupID As Nullable(Of Integer)
    Public Property SubClientFee As Nullable(Of Decimal)
    Public Property SubClientActive As Nullable(Of Boolean)

End Class
