'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TransactionData
    Public Property dataid As Integer
    Public Property TransactionReference As Nullable(Of Integer)
    Public Property TransactionDate As String
    Public Property TransactionAccountAmount As Nullable(Of Decimal)
    Public Property TransactionAccountCurrency As String
    Public Property TransactionMerchantAmount As Nullable(Of Decimal)
    Public Property TransactionMerchantCurrency As String
    Public Property TransactionMerchantNarrative As String
    Public Property TransactionMCC As String
    Public Property TransactionCardLastFourDigits As String
    Public Property ClientID As Nullable(Of Integer)
    Public Property ClientName As String
    Public Property DeploymentID As Nullable(Of Integer)
    Public Property DeploymentPlatform As String
    Public Property DeploymentChargeStart As String
    Public Property DeploymentChargeEnd As String
    Public Property DeploymentAmount As Nullable(Of Decimal)
    Public Property DeploymentCurrency As String
    Public Property DeploymentName As String
    Public Property DeploymentCreatedDate As Nullable(Of Date)
    Public Property DeploymentIdentifiers As String
    Public Property DeploymentConsumerReference As Nullable(Of Integer)
    Public Property DeploymentCustomerID As Nullable(Of Integer)
    Public Property DeploymentCustomerName As String
    Public Property SupplierName As String
    Public Property SupplierAddress1 As String
    Public Property SupplierAddress2 As String
    Public Property SupplierCity As String
    Public Property SupplierCountryCode As String
    Public Property SupplierPostalOrZipCode As String
    Public Property SupplierTelephoneNumber As String
    Public Property FacsimilieNumber As String
    Public Property SupplierConsumerID As Nullable(Of Integer)
    Public Property HotelCheckIn As String
    Public Property HotelCheckOut As String
    Public Property HotelRoomType As String
    Public Property HotelRateInformation As String
    Public Property HotelCancellationPolicy As String
    Public Property HotelCancellationReference As String
    Public Property HotelPaymentRestrictions As String
    Public Property HotelCareOfName As String
    Public Property HotelContactName As String
    Public Property HotelComments As String
    Public Property HotelBookingPlatformName As String
    Public Property Travellers As String

End Class
