//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CostImprovementAssistant.Models
{
    public partial class Assumption
    {
        public int SchemeID { get; set; }
        public int AssumptionsID { get; set; }
        public string AssumptionsDetail { get; set; }
        public string ImpactTitle { get; set; }
        public string TrustCode { get; set; }
    }
}
