//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CostImprovementAssistant.Models
{
    public partial class GeneratedIncome
    {
        public int SchemeID { get; set; }
        public string IncomeDescription { get; set; }
        public decimal? IncomeYear1SavingValueTotal { get; set; }
        public decimal? April { get; set; }
        public decimal? May { get; set; }
        public decimal? June { get; set; }
        public decimal? July { get; set; }
        public decimal? August { get; set; }
        public decimal? September { get; set; }
        public decimal? October { get; set; }
        public decimal? November { get; set; }
        public decimal? December { get; set; }
        public decimal? January { get; set; }
        public decimal? February { get; set; }
        public decimal? March { get; set; }
        public decimal? ReccurentSavingValue { get; set; }
        public decimal? ActualIncomeYear1Savings { get; set; }
        public decimal? ActualApril { get; set; }
        public decimal? ActualMay { get; set; }
        public decimal? ActualJune { get; set; }
        public decimal? ActualJuly { get; set; }
        public decimal? ActualAugust { get; set; }
        public decimal? ActualSeptember { get; set; }
        public decimal? ActualOctober { get; set; }
        public decimal? ActualNovember { get; set; }
        public decimal? ActualDecember { get; set; }
        public decimal? ActualJanuary { get; set; }
        public decimal? ActualFebruary { get; set; }
        public decimal? ActualMarch { get; set; }
        public decimal? ActualReccurentSavings { get; set; }
        public string TrustCode { get; set; }
    }
}
