//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace CostImprovementAssistant.Models
{
    public partial class QiConditionTable
    {
        public int SchemeID { get; set; }
        public string ConditionTitle { get; set; }
        public string ConditionDetail { get; set; }
        public string Mittigation { get; set; }
        public Nullable<int> Consiquence { get; set; }
        public Nullable<int> Likelyhood { get; set; }
        public Nullable<int> Score { get; set; }
        public string TrustCode { get; set; }
    }
}
