//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CostImprovementAssistant.Models
{
    public partial class QualityImpact
    {
        public int SchemeID { get; set; }
        public string ImpactDate { get; set; }
        public string CompletingQi { get; set; }
        public string Comments { get; set; }
        public int OverallRiskScore { get; set; }
        public string ReviewedBy { get; set; }
        public string Equality { get; set; }
        public string ConsiderationComments { get; set; }
        public string EvidenceComments { get; set; }
        public string ManagerDate { get; set; }
        public string ManagerStatus { get; set; }
        public string ManagerStatusComments { get; set; }
        public string EoDate { get; set; }
        public string EoStatus { get; set; }
        public string EoStatuscomments { get; set; }
        public string TrustCode { get; set; }
    }
}
