//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace CostImprovementAssistant.Models
{
    public partial class SchemeRisks
    {
        public int SchemeID { get; set; }
        public int RiskID { get; set; }
        public string SchemeRiskDetail { get; set; }
        public Nullable<int> Likelyhood { get; set; }
        public Nullable<int> Impact { get; set; }
        public string Risk { get; set; }
        public string TrustCode { get; set; }
    }
}
