//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CostImprovementAssistant.Models
{
    public partial class Staff
    {
        public int StaffID { get; set; }
        public string StaffName { get; set; }
        public string Email { get; set; }
        public string StaffPassword { get; set; }
        public bool? Administrator { get; set; }
        public bool? PM { get; set; }
        public bool? PS { get; set; }
        public bool? BS { get; set; }
        public bool? HR { get; set; }
        public bool? EO { get; set; }
        public bool? CompletingQI { get; set; }
        public bool? ReviewingQI { get; set; }
        public bool? ChiefNursing { get; set; }
        public bool? Spare1 { get; set; }
        public bool? Spare2 { get; set; }
        public bool? Active { get; set; }
        public string TrustCode { get; set; }
    }
}
