//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CostImprovementAssistant.Models
{
    public partial class Stakeholders
    {
        public int SchemeID { get; set; }
        public int StakeholdersID { get; set; }
        public string StakeholdersDetail { get; set; }
        public string Impact { get; set; }
        public string TrustCode { get; set; }
    }
}
