Imports EvoDatabaseUtils
Imports EvoUtilities.ConfigUtils

Partial Public Class ClientStatement_autogenerated

    Public Sub New()
    End Sub

    'R2.21c SA - added bookername 
    'R2.21b SA - added pLocator 
    Public Sub New(ByVal pLeadName As String, _
                    ByVal pReference As String, _
                    ByVal pPaymentTerms As Integer, _
                    ByVal pInvoiceAmount As Decimal, _
                    ByVal pAmountRecieved As Decimal, _
                    ByVal pInvoiceDate As Date, _
                    ByVal pInvoiceNumber As String, _
                    ByVal pReference2 As String, _
                    ByVal pLocator As String, _
                    ByVal pProduct As String, _
                    ByVal pBookerName As String)
        mLeadName = pLeadName
        mReference = pReference
        mPaymentTerms = pPaymentTerms
        mInvoiceAmount = pInvoiceAmount
        mAmountRecieved = pAmountRecieved
        mInvoiceDate = pInvoiceDate
        mInvoiceNumber = pInvoiceNumber
        mReference2 = pReference2
        'R2.21b SA
        mLocator = pLocator
        mProduct = pProduct
        'R2.2c SA 
        mBookerName = pBookerName
    End Sub

    Private mLeadName As String
    Private mReference As String
    Private mPaymentTerms As Integer
    Private mInvoiceAmount As Decimal
    Private mAmountRecieved As Decimal
    Private mInvoiceDate As Date
    Private mInvoiceNumber As String
    Private mReference2 As String
    'R2.21b SA
    Private mLocator As String
    Private mProduct As String
    'R2.21C SA
    Private mBookerName As String

    Public Property LeadName() As String
        Get
            Return mLeadName
        End Get
        Set(ByVal value As String)
            mLeadName = value
        End Set
    End Property

    Public Property Reference() As String
        Get
            Return mReference
        End Get
        Set(ByVal value As String)
            mReference = value
        End Set
    End Property

    Public Property PaymentTerms() As Integer
        Get
            Return mPaymentTerms
        End Get
        Set(ByVal value As Integer)
            mPaymentTerms = value
        End Set
    End Property

    Public Property InvoiceAmont() As Decimal
        Get
            Return mInvoiceAmount
        End Get
        Set(ByVal value As Decimal)
            mInvoiceAmount = value
        End Set
    End Property

    Public Property AmountRecieved() As Decimal
        Get
            Return mAmountRecieved
        End Get
        Set(ByVal value As Decimal)
            mAmountRecieved = value
        End Set
    End Property

    Public Property InvoiceDate() As Date
        Get
            Return mInvoiceDate
        End Get
        Set(ByVal value As Date)
            mInvoiceDate = value
        End Set
    End Property

    Public Property InvoiceNumber() As String
        Get
            Return mInvoiceNumber
        End Get
        Set(ByVal value As String)
            mInvoiceNumber = value
        End Set
    End Property

    Public Property Reference2 As String
        Get
            Return mReference2
        End Get
        Set(value As String)
            mReference2 = value
        End Set
    End Property

    'R2.21b SA 
    Public Property Locator As String
        Get
            Return mLocator
        End Get
        Set(ByVal value As String)
            mLocator = value
        End Set
    End Property
    'R2.21b SA 
    Public Property Product As String
        Get
            Return mProduct
        End Get
        Set(ByVal value As String)
            mProduct = value
        End Set
    End Property

    'R2.21 SA 
    Public Property BookerName As String
        Get
            Return mBookerName
        End Get
        Set(ByVal value As String)
            mBookerName = value
        End Set
    End Property

    'R2.21c SA - added bookername 
    'R2.21b SA - added locator, product
    Private Shared Function makeStatementFromRow( _
           ByVal r As IDataReader _
           ) As ClientStatement_autogenerated
        Return New ClientStatement_autogenerated( _
            clsNYS.notString(r.Item("leadname")), _
            clsNYS.notString(r.Item("reference")), _
            clsNYS.notString(r.Item("cus_ptermv")), _
            clsNYS.notDecimal(r.Item("tot_billed")), _
            clsNYS.notDecimal(r.Item("tot_recvd")), _
            CDate(r.Item("tot_invdt")), _
            clsNYS.notString(r.Item("tot_invno")), _
            clsNYS.notString(r.Item("reference2")), _
            clsNYS.notString(r.Item("locator")), _
            clsNYS.notString(r.Item("product")), _
            clsNYS.notString(r.Item("bookername")))
    End Function

    Public Shared Function getReferenceColumnValue(ByVal pColumnName As String, _
                                        ByVal pInvoiceRef As String) As String
        Using dbh As New SqlDatabaseHandle(getConfig("ConnectionString"))
            Dim strRet As String = dbh.callSPSingleValueCanReturnNothing("ClientStatement_getReferenceColumnValue", _
                                                                "@ColumnName", pColumnName, _
                                                                "@InvoiceRef", pInvoiceRef)
            Return strRet
        End Using
    End Function

    Public Shared Function getInvoices(ByVal pBossRef As String) As List(Of ClientStatement_autogenerated)
        Using dbh As New SqlDatabaseHandle(getConfig("ConnectionString"))
            Dim ret As New List(Of ClientStatement_autogenerated)()
            Using r As IDataReader = dbh.callSP("ClientStatement_getOutstandingInvoices", _
                                                "@BossId", pBossRef)
                While r.Read()
                    ret.Add(makeStatementFromRow(r))
                End While
                Return ret
            End Using
        End Using
    End Function

    Public Shared Function getColumnName(ByVal pBossRef As String) As String
        Using dbh As New SqlDatabaseHandle(getConfig("ConnectionString"))
            Dim strRet As String = CStr(dbh.callSPSingleValueCanReturnNothing("ClientStatement_getColumnName", _
                                                                              "@csd_BossRef", pBossRef))

            Return strRet
        End Using
    End Function

End Class
