//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_MI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ssoClient
    {
        public int ssoClientID { get; set; }
        public string ssoClientName { get; set; }
        public string ssoClientConfermaID { get; set; }
        public string ssoClientSbookerUrl { get; set; }
        public string ssoClientWebformsUrl { get; set; }
        public string ssoClientEtravelUrl { get; set; }
        public string ssoClientEtravelKey { get; set; }
        public string ssoClientEtravelKeyEnc { get; set; }
        public string ssoClientEtravelSiteCode { get; set; }
        public string ssoClientEvolviUrl { get; set; }
        public string ssoClientMIUrl { get; set; }
        public Nullable<int> ssoClientConfermaVersion { get; set; }
        public string ssoClientPrefix { get; set; }
        public string ssoClientPrefix2 { get; set; }
        public Nullable<bool> ssoClientIsLive { get; set; }
        public Nullable<int> ssoClientComplaintID { get; set; }
        public Nullable<bool> ssoClientUseSpecVids { get; set; }
        public Nullable<bool> ssoClientForceTraining { get; set; }
    }
}
