//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_MI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ssoUser
    {
        public int ssoUserID { get; set; }
        public string ssoUserFirstname { get; set; }
        public string ssoUserLastName { get; set; }
        public string ssoUserEmail { get; set; }
        public string ssoUserPassword { get; set; }
        public Nullable<bool> ssoUserConferma { get; set; }
        public Nullable<bool> ssoUserEtravel { get; set; }
        public Nullable<bool> ssoUserEvolvi { get; set; }
        public Nullable<bool> ssoUserSbooker { get; set; }
        public Nullable<bool> ssoUserWebforms { get; set; }
        public Nullable<int> ssoClientID { get; set; }
        public Nullable<bool> ssoUserActive { get; set; }
        public Nullable<bool> ssoUserMi { get; set; }
        public string ssoUserPasswordDate { get; set; }
        public string ssoUserOldPasswords { get; set; }
        public string ssoUserResetDate { get; set; }
        public string ssoUserSentDate { get; set; }
        public string ssoUserEvolviPassword { get; set; }
        public string ssoUserSbookerGroup { get; set; }
        public string ssoUserEbisID { get; set; }
        public Nullable<bool> ssoUserTerms { get; set; }
        public Nullable<bool> ssoUserDeleted { get; set; }
        public Nullable<bool> ssoUserTrainedEvolvi { get; set; }
        public Nullable<bool> ssoUserTrainedEtravel { get; set; }
        public Nullable<bool> ssoUserTrainedConferma { get; set; }
        public Nullable<bool> ssoUserTrainedSbooker { get; set; }
        public Nullable<System.DateTime> ssoUserDateCreated { get; set; }
        public Nullable<bool> ssoUserUnsubscribed { get; set; }
    }
}
