'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class venueSecondData
    Public Property venueSecondDataid As Integer
    Public Property ve_reference As Nullable(Of Integer)
    Public Property overview As String
    Public Property image1 As String
    Public Property image2 As String
    Public Property datecreated As Nullable(Of Date)
    Public Property lastupdated As Nullable(Of Date)
    Public Property createdby As String
    Public Property updatedby As String

End Class
