'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class venue_Deleted
    Public Property ve_reference As Integer
    Public Property ve_name As String
    Public Property ve_externalsupplier As Nullable(Of Boolean)
    Public Property ve_upload As Nullable(Of Boolean)
    Public Property ve_address1 As String
    Public Property ve_address2 As String
    Public Property to_name As String
    Public Property ve_postcode As String
    Public Property ve_gride As String
    Public Property ve_gridn As String
    Public Property co_name As String
    Public Property ar_name As String
    Public Property hg_code As String
    Public Property ve_nysrating As Nullable(Of Integer)
    Public Property ve_nyspreferred As Nullable(Of Integer)
    Public Property vt_code As String
    Public Property ve_telephone As String
    Public Property ve_fax As String
    Public Property ve_email As String
    Public Property ve_website As String
    Public Property ve_gen_femsec As Nullable(Of Boolean)
    Public Property ve_gen_iip As Nullable(Of Boolean)
    Public Property ve_gen_iso9001 As Nullable(Of Boolean)
    Public Property ve_gen_disabled As String
    Public Property ve_gen_lastinspected As String
    Public Property ve_gen_specialoffers As String
    Public Property ve_gen_commentv As String
    Public Property ve_gen_commenti As String
    Public Property boss_code As String
    Public Property ct_code As String
    Public Property ve_acc_paynet As Nullable(Of Boolean)
    Public Property ve_acc_creditlimit As Nullable(Of Double)
    Public Property ve_acc_number As String
    Public Property ve_acc_expirydate As String
    Public Property ve_acc_commission As Nullable(Of Double)
    Public Property ve_acc_roomhireonly As Nullable(Of Boolean)
    Public Property ve_rat_ddrfrom As Nullable(Of Double)
    Public Property ve_rat_ddrto As Nullable(Of Double)
    Public Property ve_rat_24from As Nullable(Of Double)
    Public Property ve_rat_24to As Nullable(Of Double)
    Public Property ve_rat_hdfrom As Nullable(Of Double)
    Public Property ve_rat_hdto As Nullable(Of Double)
    Public Property ve_rat_fdfrom As Nullable(Of Double)
    Public Property ve_rat_fdto As Nullable(Of Double)
    Public Property ve_rat_dbbfrom As Nullable(Of Double)
    Public Property ve_rat_dbbto As Nullable(Of Double)
    Public Property ve_rat_bbfrom As Nullable(Of Double)
    Public Property ve_rat_bbto As Nullable(Of Double)
    Public Property ve_rat_comment As String
    Public Property rs_code As String
    Public Property ve_fac_golf As String
    Public Property ve_fac_team As String
    Public Property ve_fac_corporate As String
    Public Property ve_fac_pool As Nullable(Of Boolean)
    Public Property ve_fac_jacuzzi As Nullable(Of Boolean)
    Public Property ve_fac_sauna As Nullable(Of Boolean)
    Public Property ve_fac_solarium As Nullable(Of Boolean)
    Public Property ve_fac_gym As Nullable(Of Boolean)
    Public Property ve_fac_comment As String
    Public Property ai_code As String
    Public Property ve_loc_airportmiles As Nullable(Of Integer)
    Public Property rw_code As String
    Public Property ve_loc_stationmiles As Nullable(Of Double)
    Public Property ve_loc_parking As Nullable(Of Boolean)
    Public Property ve_loc_parkingspaces As String
    Public Property ve_loc_parkingcost As Nullable(Of Double)
    Public Property mw_name As String
    Public Property ju_name As String
    Public Property ve_loc_comment As String
    Public Property ve_equ_laptop As Nullable(Of Double)
    Public Property ve_equ_lcd As Nullable(Of Double)
    Public Property ve_equ_flipchart As Nullable(Of Double)
    Public Property ve_equ_tvvideo As Nullable(Of Double)
    Public Property ve_equ_screen As Nullable(Of Double)
    Public Property ve_equ_ohp As Nullable(Of Double)
    Public Property ve_equ_videocamera As Nullable(Of Double)
    Public Property ve_equ_audio As Nullable(Of Double)
    Public Property ve_equ_extension As Nullable(Of Double)
    Public Property ve_equ_comment As String
    Public Property ve_con_aircon As String
    Public Property ve_con_natural As String
    Public Property ve_con_blackout As String
    Public Property ve_con_soundproof As String
    Public Property ve_con_isdn As String
    Public Property ve_con_businesscentre As Nullable(Of Boolean)
    Public Property ve_con_externalaccess As Nullable(Of Boolean)
    Public Property ve_con_teleconference As Nullable(Of Boolean)
    Public Property ve_con_videoconference As Nullable(Of Boolean)
    Public Property ve_con_noconference As Nullable(Of Integer)
    Public Property ve_con_nosyndicate As Nullable(Of Integer)
    Public Property ve_con_nobedroomsyndicate As Nullable(Of Integer)
    Public Property ve_con_ceilingheight As Nullable(Of Double)
    Public Property ve_con_comment As String
    Public Property ve_bed_noguest As Nullable(Of Integer)
    Public Property ve_bed_ensuite As Nullable(Of Boolean)
    Public Property ve_bed_nonsmoking As String
    Public Property ve_bed_safe As String
    Public Property ve_bed_minibar As String
    Public Property ve_bed_aircon As String
    Public Property ve_bed_modem As String
    Public Property ve_bed_cablesatellite As String
    Public Property ve_bed_iron As String
    Public Property ve_bed_teacoffee As String
    Public Property ve_bed_desk As String
    Public Property ve_bed_comment As String
    Public Property ve_contact As String
    Public Property ve_payeename As String
    Public Property ve_payeeaddress1 As String
    Public Property ve_payeeaddress2 As String
    Public Property ve_payeeaddress3 As String
    Public Property ve_payeepostcode As String
    Public Property ve_currency As String
    Public Property ve_EH As Nullable(Of Double)
    Public Property ve_FB As Nullable(Of Double)
    Public Property ve_RH As Nullable(Of Double)
    Public Property ve_DD As Nullable(Of Double)
    Public Property ve_EX As Nullable(Of Double)
    Public Property ve_CX As Nullable(Of Double)
    Public Property ve_cat_awards As String
    Public Property ve_cat_special As Nullable(Of Boolean)
    Public Property ve_cat_sanwich As Nullable(Of Double)
    Public Property ve_cat_buffet As Nullable(Of Double)
    Public Property ve_cat_restaurant As Nullable(Of Double)
    Public Property ve_cat_water As Nullable(Of Double)
    Public Property ve_cat_orange As Nullable(Of Double)
    Public Property ve_cat_biscuits As Nullable(Of Double)
    Public Property ve_cat_butties As Nullable(Of Double)
    Public Property ve_cat_dinner As Nullable(Of Double)
    Public Property ve_cat_privatedining As Nullable(Of Double)
    Public Property ve_cat_comments As String
    Public Property ABCID As Nullable(Of Integer)
    Public Property Photo As String
    Public Property PhotoCaption As String
    Public Property PhotoType As String
    Public Property bedrooms As String
    Public Property public_wifi As Nullable(Of Boolean)
    Public Property restaurant As Nullable(Of Boolean)
    Public Property functionrooms As String
    Public Property breakoutrooms As String
    Public Property ve_address3 As String
    Public Property editedbynys As Nullable(Of Boolean)
    Public Property insertedbynys As Nullable(Of Boolean)
    Public Property abcnysid As String
    Public Property oldname As String
    Public Property longitude As String
    Public Property lattitude As String
    Public Property exrate As String
    Public Property forecastoverride As Nullable(Of Double)
    Public Property actualoverride As Nullable(Of Double)
    Public Property overridefrom As String
    Public Property overrideto As String
    Public Property marketstandardcommission As Nullable(Of Double)
    Public Property vat As Nullable(Of Double)
    Public Property Updatedby As String
    Public Property LastUpdated2 As Nullable(Of Date)
    Public Property LastUpdated As Nullable(Of Date)
    Public Property cannotMapFlag As Nullable(Of Integer)
    Public Property alternativepostcode As String
    Public Property useNYSdata As Nullable(Of Integer)
    Public Property useNYSmeetingrooms As Nullable(Of Integer)
    Public Property centraltel As String
    Public Property ve_loc_noparking As Nullable(Of Boolean)
    Public Property commisioninvoiceemail As String
    Public Property ve_gen_greenscheme As String
    Public Property ve_gen_iso14001 As Nullable(Of Boolean)
    Public Property ve_loc_tubestation As String
    Public Property ve_loc_tubestationmiles As Nullable(Of Double)
    Public Property noncom As Nullable(Of Boolean)
    Public Property noncommchecked As Nullable(Of Boolean)
    Public Property stopAutoInvoiceChaser As Nullable(Of Boolean)
    Public Property wifi As Nullable(Of Boolean)
    Public Property confermachasingemail As String
    Public Property bsh As Nullable(Of Boolean)
    Public Property ve_vatnumber As String
    Public Property mevischasingemail As String
    Public Property ve_loc_junctionmiles As Nullable(Of Double)
    Public Property ve_fac_spa As Nullable(Of Boolean)
    Public Property ve_fac_lesureclub As Nullable(Of Boolean)
    Public Property ve_fac_golfcheck As Nullable(Of Boolean)
    Public Property ve_fac_teamcheck As Nullable(Of Boolean)
    Public Property ve_fac_corporatecheck As Nullable(Of Boolean)
    Public Property ve_fac_outsidecheck As Nullable(Of Boolean)
    Public Property ve_fac_outside As String
    Public Property ve_fac_restaurant As String
    Public Property ve_fac_roomservice As String
    Public Property ve_fac_bar As String
    Public Property ve_fac_restaurantcheck As Nullable(Of Boolean)
    Public Property ve_fac_barcheck As Nullable(Of Boolean)
    Public Property sendCreditCardForm As Nullable(Of Boolean)

End Class
