'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Venue_SearchType
    Public Property venue_SearchTypeID As Integer
    Public Property Description As String
    Public Property Value As Nullable(Of Integer)

End Class
