'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class VenueDBMeetingRoom
    Public Property VenueDBMeetingRoomID As Integer
    Public Property VenueNYSREF As Nullable(Of Integer)
    Public Property VenueDBID As Nullable(Of Integer)
    Public Property roomename As String
    Public Property theatre As Nullable(Of Integer)
    Public Property theatre_BP As Nullable(Of Integer)
    Public Property classroom As Nullable(Of Integer)
    Public Property classroom_bp As Nullable(Of Integer)
    Public Property ushape As Nullable(Of Integer)
    Public Property boardroom As Nullable(Of Integer)
    Public Property hollowsq As Nullable(Of Integer)
    Public Property cocktail As Nullable(Of Integer)
    Public Property dinner As Nullable(Of Integer)
    Public Property banquet As Nullable(Of Integer)
    Public Property dinnerdance As Nullable(Of Integer)
    Public Property reception As Nullable(Of Integer)
    Public Property cabaret As Nullable(Of Integer)
    Public Property cabaret_bp As Nullable(Of Integer)
    Public Property staging As Nullable(Of Boolean)
    Public Property disabledaccess As Nullable(Of Boolean)
    Public Property halfday As String
    Public Property fullday As String
    Public Property roomlength As Nullable(Of Double)
    Public Property roomwidth As Nullable(Of Double)
    Public Property roomheight As Nullable(Of Double)
    Public Property aircon As Nullable(Of Boolean)
    Public Property naturallight As Nullable(Of Boolean)
    Public Property blackout As Nullable(Of Boolean)
    Public Property videoconference As Nullable(Of Boolean)
    Public Property vehicleaccess As Nullable(Of Boolean)

End Class
