'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class NYSDBEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=NYSDBEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property venue() As DbSet(Of venue)
    Public Overridable Property venue_Deleted() As DbSet(Of venue_Deleted)
    Public Overridable Property Venue_SearchType() As DbSet(Of Venue_SearchType)
    Public Overridable Property venue_type() As DbSet(Of venue_type)
    Public Overridable Property VenueDBMeetingRoom() As DbSet(Of VenueDBMeetingRoom)
    Public Overridable Property venuegrouppreference() As DbSet(Of venuegrouppreference)
    Public Overridable Property venueOption() As DbSet(Of venueOption)
    Public Overridable Property venuepreference() As DbSet(Of venuepreference)
    Public Overridable Property venueSecondData() As DbSet(Of venueSecondData)

End Class
