'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class venuegrouppreference
    Public Property venuegrouppreferenceid As Integer
    Public Property groupid As Nullable(Of Integer)
    Public Property hg_id As Nullable(Of Integer)
    Public Property venuegrouppreferencevalue As Nullable(Of Integer)
    Public Property datecreated As Nullable(Of Date)
    Public Property lastupdated As Nullable(Of Date)
    Public Property createdby As String
    Public Property updatedby As String
    Public Property companyid As Nullable(Of Integer)

End Class
