'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class venueOption
    Public Property venueOptionID As Integer
    Public Property groupid As Nullable(Of Integer)
    Public Property venueReference As Nullable(Of Integer)
    Public Property hideFromClient As Nullable(Of Boolean)
    Public Property hideFromAllClients As Nullable(Of Boolean)

End Class
